---
title: "Homework 3"
subtitle: "ECON 470, Spring 2025"
author: "Ethan Murakami"
format:
  pdf:
    output-file: "murakami_e_hmwk2_s1"
    output-ext:  "pdf"
    header-includes:
      - \usepackage{float}
      - \floatplacement{table}{H}
---

```{r}
#| include: false

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes, fixest,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel, survey, foreign, devtools, pdftools, kableExtra, modelsummary,
               kableExtra)
```

Here is a link to my repository: {https://github.com/bemur3/hmwk3}

\newpage 

```{r}
#| include: false
#| eval: true


load("/Users/ethanmurakami/Documents/GitHub/hmwk3/submission1/Hwk3_workspace.Rdata")
```


\newpage 

## 1. Present a bar graph showing the proportion of states with a change in their cigarette tax in each year from 1970 to 1985.

```{r} 
#| echo: false
#| label: tax.changeplot

print(tax.change.plot)
```


\newpage 

## 2. 

```{r} 
#| echo: false
#| label: avtgtax.priceplot

print(avtgtax.price.plot)
```

\newpage

## 3. 

```{r} 
#| echo: false
#| label: top.statesplot

print(top.states.plot)
```

\newpage

## 4. 

```{r} 
#| echo: false
#| label: bottom.statesplot

print(bottom.states.plot)
```

\newpage

## 5. 

```{r} 
#| echo: false
#| label: mergedstatesplot

print(merged.states.plot)
```

\newpage

## 6. 

```{r} 
#| echo: false
#| label: elasticity_model

summary(elasticity_model)
```

\newpage

## 7. 

```{r} 
#| echo: false
#| label: iv_model

summary(iv_model)
```

\newpage

## 8. 

```{r} 
#| echo: false
#| label: me

summary(first_stage)
summary(reduced_form)
```

\newpage

## 9. 

```{r} 
#| echo: false
#| label: 1990-2015

summary(elasticity_model_b)
summary(iv_model_b)
summary(first_stage_b)
summary(reduced_form_b)
```

\newpage

## 10. 

```{r} 
#| echo: false
#| label: elasticity_comparison_table

print(elasticity_comparison)
```


